Repository ether/etherpad-lite, pull requests merged in 2020-06, with the labels that each got.

#3829 Tests url import export
  src/package.json
  tests/backend/fuzzImportTest.js
  tests/backend/specs/api/fuzzImportTest.js
  tests/backend/specs/api/image.png
  tests/backend/specs/api/importexportGetPost.js
  tests/backend/specs/api/test.doc
  tests/backend/specs/api/test.txt
Labels: tests

#3965 Setting for allowing import - Ready for Review / Merge
  settings.json.template
  src/node/handler/PadMessageHandler.js
  src/node/hooks/express/importexport.js
  src/node/utils/Settings.js
  src/static/js/pad_editbar.js
Labels: Bug, Export/Import

#4008 bin: Various shell script cleanups
  bin/buildForWindows.sh
  bin/debugRun.sh
  bin/installDeps.sh
  bin/run.sh
  bin/safeRun.sh
Labels: stale code

#4017 Various UI improvement
  src/static/css/iframe_editor.css
  src/static/css/pad.css
  src/static/css/pad/fonts.css
  src/static/css/pad/form.css
  src/static/css/timeslider.css
  src/static/font/Aleygreya-ExtraBold.woff
  src/static/font/Aleygreya-ExtraBold.woff2
  src/static/font/Aleygreya-Medium.woff
  src/static/font/Aleygreya-Medium.woff2
  src/static/js/ace2_inner.js
  src/static/js/broadcast_slider.js
  src/static/skins/colibris/pad.css
  src/static/skins/colibris/src/general.css
  src/static/skins/colibris/src/layout.css
  src/static/skins/colibris/src/pad-editor.css
  src/static/skins/colibris/src/pad-variants.css
  src/static/skins/colibris/src/plugins/font_color.css
  src/templates/pad.html
  src/templates/timeslider.html
Labels: UI

#3823 Use worker threads to minify JS/CSS files
  src/node/utils/Minify.js
  src/node/utils/MinifyWorker.js
  src/package-lock.json
  src/package.json
Labels: performance

#3769 Fix3032 - importing document botches pad options
  src/static/js/pad.js
Labels: Export/Import, editor

#3842 Decrementindent on ol and ul button press - ready for review but don't merge
  src/static/js/ace2_inner.js
Labels: Feature Request, UX, editor

#3877 Clean HTML prior to import & Content Collector test coverage - READY FOR REVIEW
  package-lock.json
  src/node/utils/ExportHelper.js
  src/node/utils/ExportHtml.js
  src/node/utils/ImportHtml.js
  src/node/utils/Minify.js
  src/package-lock.json
  src/package.json
  src/static/js/contentcollector.js
  src/static/js/linestylefilter.js
  src/templates/export_html.html
  test.js
  tests/backend/specs/api/pad.js
  tests/backend/specs/contentcollector.js
  tests/frontend/travis/runnerBackend.sh
Labels: Bug, Export/Import, editor

#3771 Mega test thread for OL / UL #3712 - DO NOT MERGE - This is Test Coverage ONLY, these tests should fail.
  test.js
  tests/backend/specs/api/importexport.js
  tests/frontend/specs/ordered_list.js
  tests/frontend/specs/unordered_list.js
Labels: UX, editor, tests

#3991 Include pool every 100 revs - Ready for Testing / Merge
  src/node/db/Pad.js
Labels: changesets

#3983 Clearauthorship on full doc selected - Ready for review/merge
  src/static/js/pad_editbar.js
Labels: UX, editor

#4073 Timeslider export links numeric pads
  src/static/js/timeslider.js
  tests/frontend/specs/timeslider_numeric_padID.js
Labels: Bug, Export/Import, timeslider

#4075 Stale code: Terser instead of uglify
  src/node/utils/Minify.js
  src/node/utils/MinifyWorker.js
  src/package-lock.json
  src/package.json
Labels: performance, stale code

#3903 bump to jQuery 3
  src/static/js/jquery.js
  src/static/js/pluginfw/client_plugins.js
Labels: stale code
