Repository ether/etherpad-lite, pull requests merged in 2020-04, with the labels that each got.

#3818 Set author info error - Ready for Review / Merge [urgent]
  src/static/js/ace.js
Labels: Serious Bug

#3841 Rewrite the customError module with class syntax
  src/node/utils/customError.js
Labels: stale code

#3765 Add env var for defaultPadText
  doc/docker.md
  settings.json.docker
  settings.json.template
  src/node/utils/Settings.js
Labels: docker

#3766 docker: add support for arbitrary user ids (OpenShift compatibility)
  Dockerfile
Labels: docker

#3886 docker: build & run the container in production mode
  Dockerfile
  doc/docker.md
Labels: docker

#3922 Skin builder: add coma in resulting code #3919
  src/static/js/skin_variants.js
Labels: new-skin

#3918 chore(docker): removing git-objects from final docker image
  .dockerignore
Labels: docker

#3929 doc: remove old vendorized marked module and replace with 0.8.2
  Makefile
  bin/doc/node_modules/.bin/marked
  bin/doc/node_modules/marked/.npmignore
  bin/doc/node_modules/marked/LICENSE
  bin/doc/node_modules/marked/Makefile
  bin/doc/node_modules/marked/README.md
  bin/doc/node_modules/marked/bin/marked
  bin/doc/node_modules/marked/index.js
  bin/doc/node_modules/marked/lib/marked.js
  bin/doc/node_modules/marked/man/marked.1
  bin/doc/node_modules/marked/package.json
  bin/doc/package-lock.json
  bin/doc/package.json
Labels: docs

#3904 Improved browser language (navigator.language) support
  src/static/js/html10n.js
Labels: i18n

#3925 Fix duplicated iframes after importing text in a pad
  src/static/js/pad.js
Labels: Bug, Export/Import, UI

#3942 windows: bump the node version included in the prebuilt package
  bin/buildForWindows.sh
Labels: windows

#3941 ZERO reported vulnerabilities in Etherpad 1.8.3
  src/package-lock.json
  src/package.json
Labels: dependencies, security

#3934 Fix inconsistencies when deleting content while timeslider is open
  src/static/js/Changeset.js
Labels: Bug
